version: 2
mergeable:
  - when: pull_request.*
    validate:
      - do: description
        no_empty:
          enabled: true
          message: Description matter and should not be empty. Provide detail with **what** was changed, **why** it was changed, and **how** it was changed.
      - do: title
        must_include:
          regex: ^(\[DEVELOP\]|\[FEATURE\]|\[HOTFIX\]|\[RELEASE\]|\[QA\]) [a-zA-Z0-9]+.*
      - do: headRef
        must_include:
          regex: '^(develop|feature|hotfix|release|qa)\/[a-zA-Z]+-[0-9]+-.*'
          message: 'Your branch name should be like feature/SOME-TICKET-NUMBER-some-description'
      - do: approvals
        min:
          count: 2
          message: 'The pull request must be aproved by minimum 2 reviewers'
